development:
  adapter: postgresql
  database: backbone_data_bootstrap_development
  min_messages: WARNING
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: backbone_data_bootstrap_test
  min_messages: WARNING
  host: localhost
  pool: 5
